CREATE TABLE google_oauth_states (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT,
  state TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (DATETIME(created_at) IS NOT NULL),
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (DATETIME(updated_at) IS NOT NULL)
);
