CREATE TABLE google_links (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT,
  access_token TEXT NOT NULL,
  token_type TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at TEXT NOT NULL CHECK (DATETIME(expires_at) IS NOT NULL),
  scope TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (DATETIME(created_at) IS NOT NULL),
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (DATETIME(updated_at) IS NOT NULL)
);
