CREATE TABLE users (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (DATETIME(created_at) IS NOT NULL),
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP CHECK (DATETIME(updated_at) IS NOT NULL)
);
