name: Build
on:
  release:
    types: [published]
jobs:
  build:
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Linux x86_64
            goos: linux
            goarch: amd64
          - name: Linux ARM
            goos: linux
            goarch: arm
          - name: macOS Intel
            goos: darwin
            goarch: amd64
          - name: macOS Apple Silicon
            goos: darwin
            goarch: arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        uses: wangyoucao577/go-release-action@master
        with:
          release_tag: ${{ env.GITHUB_REF }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: ${{ matrix.goarch }}
          goos: ${{ matrix.goos }}
          ldflags: -X main.version=${{ env.GITHUB_REF }}
          md5sum: false
          sha256sum: true
