on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [arm, amd64]
    steps:
      - name: Set APP_VERSION env
        run: echo $(git describe --tags) > /github/workspace/version
      - name: Build
        uses: wangyoucao577/go-release-action@v1.13
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: ${{ matrix.goarch }}
          goos: ${{ matrix.goos }}
          goversion: "https://dl.google.com/go/go1.16beta1.linux-amd64.tar.gz"
          ldflags: "-X main.version=$(cat /github/workspace/version)"
          md5sum: false
          sha256sum: true
