name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: minor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: wangyoucao577/go-release-action@master
        with:
          release_tag: ${{ steps.release.outputs.tag_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: arm
          goos: linux
          ldflags: -X main.version=${{ steps.release.outputs.version }}
          md5sum: false
          sha256sum: true
