on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [arm, amd64]
    steps:
      - uses: actions/checkout@v2

      - uses: wangyoucao577/go-release-action@v1.14
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: ${{ matrix.goarch }}
          goos: ${{ matrix.goos }}
          goversion: https://dl.google.com/go/go1.16beta1.linux-amd64.tar.gz
          ldflags: -X main.version=$GITHUB_SHA
          md5sum: false
          sha256sum: true
