name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Create release
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload:
    needs: release
    name: Upload artifacts
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Package static files
        env:
          GOBIN: ${{ github.workspace }}
        run: |
          go install github.com/markbates/pkger/cmd/pkger
          # -o <package you'll use pkger in> -include <loc of static files>
          ./pkger -o db -include /db/migrations
          ./pkger -o web -include /web/html
      - name: Release x86 ${{ matrix.os }}
        uses: wangyoucao577/go-release-action@master
        with:
          release_tag: ${{ steps.release.outputs.tag_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: amd64
          ldflags: -X main.version=${{ steps.release.outputs.version }}
          md5sum: false
          sha256sum: true
      - name: Release ARM ${{ matrix.os }}
        uses: wangyoucao577/go-release-action@master
        with:
          release_tag: ${{ steps.release.outputs.tag_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: arm
          ldflags: -X main.version=${{ steps.release.outputs.version }}
          md5sum: false
          sha256sum: true
