on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [arm, amd64]
    steps:
    - uses: actions/checkout@v2
    - name: Set APP_VERSION env
      run: export APP_VERSION=$(git describe --tags)
    - uses: wangyoucao577/go-release-action@v1.13
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goarch: ${{ matrix.goarch }}
        goos: ${{ matrix.goos }}
        goversion: 1.16beta1
        ldflags: "-X main.version=${{ env.APP_VERSION }}"
        md5sum: false
        sha256sum: true
