name: Release
on:
  push:
    branches:
      - main
jobs:
  bump:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package static files
        env:
          GOBIN: ${{ github.workspace }}
        run: |
          go install github.com/markbates/pkger/cmd/pkger
          # -o <package you'll use pkger in> -include <loc of static files>
          ./pkger -o db -include /db/migrations
          ./pkger -o web -include /web/html
