name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package static files
        env:
          GOBIN: ${{ github.workspace }}
        run: |
          go install github.com/markbates/pkger/cmd/pkger
          # -o <package you'll use pkger in> -include <loc of static files>
          ./pkger -o db -include /db/migrations
          ./pkger -o web -include /web/html
      - name: Release x86 Linux
        uses: wangyoucao577/go-release-action@master
        env:
          CGO_ENABLED: 1
        with:
          release_tag: ${{ steps.release.outputs.tag_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: amd64
          goos: linux
          ldflags: -X main.version=${{ steps.release.outputs.version }}
          md5sum: false
          sha256sum: true
      - name: Release ARM Linux
        uses: wangyoucao577/go-release-action@master
        env:
          CC: arm-linux-gnueabihf-gcc
          CGO_ENABLED: 1
        with:
          release_tag: ${{ steps.release.outputs.tag_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: arm
          goos: linux
          ldflags: -X main.version=${{ steps.release.outputs.version }}
          md5sum: false
          sha256sum: true
      - name: Release Intel macOS
        uses: wangyoucao577/go-release-action@master
        env:
          CGO_ENABLED: 1
        with:
          release_tag: ${{ steps.release.outputs.tag_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: amd64
          goos: darwin
          ldflags: -X main.version=${{ steps.release.outputs.version }}
          md5sum: false
          sha256sum: true
